/* English to Broad Norfolk Translator */
var broadNorfolk = {
	translatePhrase: function(phrase) {
		var trans = "";
		var lines = phrase.split(/[\n\r]+/);
		for (line in lines) {
			trans = trans + "<p>";
			var words = lines[line].split(/\s+/);
			for (word in words) {
				var fix = words[word].replace(/^([^A-Za-z'\-]*?)([A-Za-z'\-]*)([^A-Za-z'\-]*?)$/, "$1 $2 $3").split(" ");
				trans = trans + fix[0] + this.translateWord(fix[1]) + fix[2] + " ";
			}
			trans = trans + "</p>";
		}
		return trans;
	},
	translateWord: function(word) {
		/* Remove and remember plural, if any */
		var plural = "";
		if (/[Ss]$/.test(word)) {
			plural = word.charAt(word.length - 1);
			word = word.substring(0, word.length - 1);
		}
		var trans = word;
		var lower = word.toLowerCase()
		if (this.words.hasOwnProperty(lower)) {
			/* Replace known word */
			if (/^[a-z'\-]+$/.test(word)) {
				/* Lower case */
				trans = this.words[lower];
			} else if (/^[A-Z'\-]+$/.test(word)) {
				/* Upper case */
				trans = this.words[lower].toUpperCase();
			} else {
				/* Mixed case */
				trans = this.words[lower];
				trans = trans.charAt(0).toUpperCase() + trans.slice(1);
			}
		} else {
			/* Replace syllables */
			for (syllable in broadNorfolk.syllables) {
				trans = trans.replace(syllable, this.syllables[syllable]);
				trans = trans.replace(syllable.toUpperCase(), this.syllables[syllable].toUpperCase());
			}
		}
		return trans + plural;
	},
	/* Replacement syllables */
	syllables: {
		"igh": "oigh",
		"uic": "ooc",
		"ur": "oor",
		"ing": "in'",
		"ly": "lie",
		"ar": "aar",
		"t": "'"
	},
	/* Replacement words */
	words: {
		"abcess": "abser",
		"acre": "airca",
		"across": "accrorst",
		"after": "ar'er",
		"again": "agin",
		"against": "agin",
		"aggravating": "ickeny",
		"agile": "kedgy",
		"agony": "clorth",
		"agreement": "agreeance",
		"agricultural": "adjricultural",
		"aint": "in",
		"airs": "frame",
		"alley": "looke",
		"alone": "aloon",
		"already": "ariddy",
		"always": "allust",
		"angry": "raw",
		"annoy": "wurri",
		"ant": "pishamire",
		"appear": "appare",
		"april": "airpril",
		"apron": "slop",
		"argue": "higgle",
		"argument": "barney",
		"argument": "barnies",
		"as": "bairn uz",
		"ask": "ax",
		"askew": "soshens",
		"attempt": "imatair",
		"attempt to": "fare-a",
		"awkward": "occard",
		"axel": "ackulster",
		"babble": "hack-slarverin",
		"bad-tempered": "raw",
		"badly": "bad",
		"bag": "pook",
		"bargain": "higgle",
		"barren": "gast",
		"basin": "bairsn",
		"basket": "ped",
		"batteries": "ba-a'ries",
		"battery": "ba-arie",
		"bawl": "oller",
		"beachcombing": "pawkin",
		"beating": "troshin",
		"beat": "thack",
		"beautiful": "boo-ful",
		"beer": "bare",
		"before": "afore",
		"behind": "ahoind",
		"being": "bairn",
		"been": "bairn",
		"beer": "bear",
		"belch": "brork",
		"bell": "bal",
		"belly": "pod",
		"stomach": "pod",
		"bend down": "pop",
		"better": "ba'er",
		"between": "atwin",
		"bike": "boik",
		"cycle": "boik",
		"bicycle": "boik",
		"bird": "baad",
		"birth": "baath",
		"birthday": "baath",
		"black eye": "swors'on wynder",
		"bloke": "blook",
		"blow": "ding",
		"boat": "boo",
		"blunt": "bezzle",
		"boil": "push",
		"boisterous": "hossin abou'",
		"bolt": "yarm",
		"bone": "boon",
		"bonfire": "flagfoir",
		"fire": "foir",
		"boot": "bu'e",
		"borrow": "bara",
		"boss": "stiffler",
		"bossy": "bigga'y",
		"bottle": "baa'l",
		"box": "clip",
		"boy": "boo-i",
		"break": "brairk",
		"rubble": "collder",
		"brittle": "spol'",
		"broken": "brook",
		"broke": "brook",
		"brought": "brung",
		"bullrushes": "bolders",
		"bump": "bunny",
		"bundle": "bol'",
		"burn": "baan",
		"busy": "stifler",
		"can": "ken",
		"cannot": "car'",
		"carol singers": "mumpers",
		"carriage": "trap",
		"catch": "cop-owld",
		"causeway": "carnser",
		"certificate": "sustificate",
		"chamber pot": "guzunder",
		"chat": "mardle",
		"cheek": "chap",
		"cheeky": "silla-bowld",
		"cheerio": "chairioo",
		"goodbye": "chairioo",
		"children": "childer",
		"chimney": "chimbley",
		"choke": "chook",
		"choked": "quackled",
		"chosen": "chooz",
		"church": "chaach",
		"clear": "clare",
		"clear out": "foi-ou",
		"clever": "hoigh-larned",
		"close": "clooss",
		"closed": "cloosed",
		"closely": "nare",
		"closing": "cloosin'",
		"clump": "carr",
		"clumsy": "fumble-fisted",
		"coax": "cooch",
		"cobblers": "snobs",
		"cocoa": "cuckoo",
		"coffee": "corffy",
		"coffin": "corffen",
		"cold": "cowld",
		"comb": "coom",
		"comb-out": "clag",
		"complication": "dibble",
		"confusion": "pucka'ry",
		"controversy": "squi'",
		"conversation": "mardle",
		"cope": "coop",
		"cot": "caa'",
		"cough": "corff",
		"crease": "ruck",
		"creeping": "crimlan",
		"crisp": "spol'",
		"crossroads": "fowlete",
		"crowd": "scrouge",
		"crowded": "crod",
		"crunchy": "churkey",
		"crushed": "jammed",
		"crust": "cruckle",
		"cry": "blar",
		"cupola": "cubelow",
		"curry": "carney",
		"curtsey": "bop",
		"daft": "sorf'",
		"daisy": "dairzy",
		"dam": "stank",
		"damp": "daggly",
		"dare": "daast",
		"dawdle": "sarn'er",
		"dealer": "higgler",
		"dear": "dare",
		"deck": "plankway",
		"decorate": "tricalair",
		"dent": "din'",
		"determined": "nairler",
		"devoted": "devoo'd",
		"devote": "devoo",
		"dew": "dag",
		"dickey": "chea'",
		"difference": "diffus",
		"difficult": "ickeny",
		"difficulties": "dibbles",
		"didn't": "din'",
		"disagreeable": "puuk",
		"disappointed": "done",
		"discharge": "suu",
		"ditherer": "dardalum-do",
		"dog": "dorg",
		"doing": "durn",
		"dollop": "lickup",
		"domineering": "nairler",
		"don't": "doon'",
		"donkey": "dickey",
		"doubt": "dou",
		"downcast": "done",
		"downpour": "reamer",
		"drain": "cockey",
		"drawl": "dran'",
		"dribble": "slarverin",
		"dripping": "seam",
		"drizzle": "smur",
		"drove": "driv",
		"drunk": "slewed",
		"drying": "hairze",
		"dumplings": "dumplans",
		"dunes": "denes",
		"dust": "stew",
		"dustpan": "firplen",
		"duty": "doo'y",
		"dyke": "deke",
		"ear": "lug",
		"earwig": "pishamire barnybee",
		"eaten": "e'",
		"educated": "hoigh-larned",
		"elbow": "alba",
		"eleven": "levven",
		"else": "alss",
		"empty": "whalm",
		"enormous": "sooler",
		"enough": "enow",
		"evacuees": "vacajees",
		"ewer": "gotch",
		"exact": "zack",
		"exactly": "zacklie",
		"expert": "dabster",
		"extreme": "rare",
		"extremely": "rare",
		"faded": "dumduckerdumer",
		"fairy": "pharisee",
		"famished": "clammed",
		"famous": "fairmous",
		"farthing": "farden",
		"fasten": "hank-up",
		"fastiduous": "narsty-patic'la",
		"fault": "fau'",
		"favour": "carney",
		"fear": "fare",
		"feet": "fi'en",
		"fell": "fal",
		"fenmen": "yaller-ballies",
		"fidget": "jiffle",
		"fierce": "fairce",
		"fingerstall": "hu'kin",
		"fitting": "matchly",
		"floater": "floo'er",
		"floor": "plancher",
		"floorcloth": "dwoil",
		"fool": "fule",
		"fooling": "annakin",
		"foreman": "hid stiffler",
		"foundation": "groundsel",
		"four": "fower",
		"frame": "frairm",
		"fretful": "pensy",
		"frightened": "frit",
		"fright": "froi'",
		"frog": "fresher",
		"frost": "frorst",
		"froze": "friz",
		"frozen": "frawn",
		"fry": "froise",
		"fussy": "finnacky",
		"gadget": "pairk",
		"gaggle": "scalder",
		"gain": "gairn",
		"game": "gairm",
		"gate": "gair'",
		"gave": "gan",
		"gear": "gare",
		"germinate": "chick",
		"get": "gi'",
		"ghost": "hoigh-sproi'e",
		"girl": "mawther",
		"girth": "gaath",
		"go": "goo",
		"goal": "ghoul",
		"goat": "goo'",
		"going": "gorn",
		"gooseberry": "guzegog",
		"gooseberries": "guzegogs",
		"gossip": "mardle",
		"grab": "fang-howld",
		"great": "gri'",
		"greyhound": "long dorg",
		"grin": "gaan",
		"gristle": "paxwax",
		"gulp": "golp",
		"gusty": "gushy",
		"guzzle": "bezzle",
		"gypsy": "diddecoy",
		"hands": "plawks",
		"happened": "'appened",
		"haunt": "haun'",
		"have": "hev",
		"haven't": "in'",
		"haze": "hairz",
		"he has": "here",
		"head": "hid",
		"hear": "hare",
		"heard": "haad",
		"hearty": "bruff",
		"heated": "he'",
		"hedge sparrow": "dunnock",
		"hell": "hal",
		"hello": "halloo",
		"help": "'alp",
		"hen": "hin",
		"here": "'are",
		"heron": "harnser",
		"himself": "'issalf",
		"hind": "'oinderpar'",
		"hinge": "jimmer",
		"hither": "'oinder",
		"hoe": "hoo",
		"hoed": "hew",
		"hoeing": "harn",
		"hold": "'owld",
		"hole": "dook",
		"holiday": "aarldie",
		"hollow": "'oller",
		"holy": "hooly",
		"home": "hoom",
		"honest": "jannock",
		"hope": "'oop",
		"horseplay": "nonnickin",
		"houses": "housen",
		"how": "hew",
		"however": "howsome-ever",
		"howling": "duller",
		"huge": "ooj",
		"hundred": "hundre'",
		"hurl": "hull",
		"hurrying": "hossin along",
		"hysteric": "highstirrick",
		"i": "oi",
		"i have": "our",
		"idea": "oidare",
		"if": "do",
		"ill": "quare",
		"imitate": "imitair'",
		"improve": "chip-up",
		"indemnified": "damnified",
		"independent": "uproigh'",
		"inflamed": "angry",
		"insolence": "chalp",
		"instead": "instid",
		"isn't": "in'",
		"isn't it": "inta",
		"it": "tha'",
		"is not": "in'",
		"job": "jaab",
		"join in": "mow in",
		"july": "juloi",
		"just": "jist",
		"kettle": "betsy",
		"kilter": "kel'er",
		"knock": "ja'er",
		"knowing": "narn",
		"knowledge": "know",
		"ladybird": "bishy-barnabee",
		"lame": "'impy-lairm",
		"lane": "drift",
		"lanky": "squinny",
		"last": "larst",
		"latch": "cetch",
		"late": "lair'",
		"lately": "lair'ly",
		"laugh": "gollder",
		"laughter": "gollder",
		"lavatory": "pe'y",
		"lazy": "lairzy",
		"leader": "stiffler",
		"leak": "run",
		"lean": "squinny",
		"leaned": "len'",
		"leapfrog": "huck-a-buck",
		"learn": "larn",
		"leather": "laather",
		"letter": "la'er",
		"lie": "loi",
		"limp": "himp",
		"load": "lood",
		"loft": "soller",
		"loop": "lupe",
		"lope": "lampen'",
		"lot": "soigh'",
		"lug": "lig",
		"lumpy": "claggy",
		"lunch": "daarky",
		"make": "mairk",
		"mallet": "bee'l",
		"malted": "maal'ed",
		"mate": "bor",
		"matter": "signifoi",
		"meadow": "midder",
		"mean": "stinjy",
		"medicine": "physic",
		"mere": "mare",
		"mice": "meezen",
		"michaelmas": "packrag day",
		"midges": "mingins",
		"midnight": "bull's nune",
		"midwifery": "nijjer'in",
		"mighty": "a bramah",
		"mile": "moil",
		"mistlethrush": "fullfer",
		"mist": "dag",
		"mite": "smi'ock",
		"moderate": "maadra",
		"money": "kew'er",
		"moon": "mune",
		"moth": "morth",
		"motor": "moo-er",
		"car": "moo-er",
		"mow": "moo",
		"mower": "mar",
		"mowing": "marn",
		"mud": "slub",
		"muddle": "puckaterry",
		"muddy": "dauby",
		"mutter": "pu'er",
		"muzzled": "cooped",
		"my": "moi",
		"name": "nairm",
		"native": "nair'av",
		"natterjack": "runnen",
		"near": "nare",
		"needs": "warn'",
		"neither": "nayther",
		"nerves": "wick",
		"nests": "neezen",
		"net": "lin'",
		"never": "navver",
		"new year's eve": "owl yare's noigh'",
		"nice": "noice",
		"night": "noight",
		"nine": "noin",
		"no": "noo",
		"nobody": "noobardy",
		"noise": "lumberin",
		"none": "noon",
		"nonsense": "squi'",
		"norfolk": "norfook",
		"norwich": "norridge",
		"nosing": "peerkin",
		"nothing": "naathin",
		"november": "noovember",
		"number": "mor'",
		"october": "octoober",
		"of": "f",
		"off": "orff",
		"office": "orffas",
		"officiate": "fisherair'",
		"offset": "on the sosh",
		"often": "orfen",
		"old": "owl'",
		"on end": "anend",
		"on top": "a top",
		"only": "oolly",
		"open": "oopen",
		"operation": "operairtion",
		"oppressive": "thongy",
		"or": "do",
		"over": "oover",
		"owed": "ewe",
		"owing": "arn",
		"pain": "jip",
		"pancake": "froise",
		"panic": "stew",
		"paper": "pairper",
		"parish": "nair'av",
		"past": "parst",
		"paving bricks": "clinkers",
		"peculiar": "rum",
		"pencil": "cedar",
		"perch": "perk",
		"pests": "minnafers",
		"petition": "brief",
		"petty": "pe'y",
		"piano": "joanna",
		"picture": "cu'",
		"piece": "choif",
		"pint": "point",
		"place": "plairce",
		"plain": "plairn",
		"plantation": "plantin",
		"plate": "plair'",
		"plenty": "ple'y",
		"pneumonia": "pumony",
		"pocket watch": "tannup",
		"poem": "porm",
		"poke": "pook",
		"poor": "pore",
		"poorly": "sadly",
		"butcher": "kiderer",
		"post": "poost",
		"pram": "cooch",
		"prick": "pritch",
		"prim": "primmicky",
		"probe": "proog",
		"prosper": "moise",
		"proud": "coddy",
		"puddle": "swidge",
		"pullover": "garnsey",
		"push": "shuft",
		"quarter": "kor'er",
		"queer": "quare",
		"quay": "staithe",
		"rabbit": "cooney",
		"racket": "ra'ock",
		"radio": "rairdioo",
		"rafters": "spars",
		"ragged": "daggly",
		"rain": "rairn",
		"rake": "croome",
		"rancid": "reasty",
		"rascal": "noin'er",
		"rate": "rair'",
		"ready": "riddy",
		"rear": "rare",
		"reprimand": "mob",
		"resemble": "blee",
		"right": "roight",
		"road": "rood",
		"rode": "rid",
		"room": "rume",
		"rough": "rude",
		"rowing": "rarn",
		"rubbish": "rubbidge",
		"rumour": "roomen'",
		"rumple": "frumple",
		"rush basket": "frairl",
		"rushes": "seggs",
		"sack": "pook",
		"same": "sairm",
		"sandhills": "merrimills",
		"savage": "sa-a-vage",
		"saved": "sef'",
		"scarecrow": "mawkin",
		"scatter": "shug",
		"scoff": "scorff",
		"scoop": "scuppi'",
		"scrap": "chair'",
		"scratch": "scrab",
		"scruffy": "rude",
		"scythe": "juloi rairzor",
		"season": "seal",
		"seed": "sed",
		"seesaw": "ti'amator'er",
		"seem": "fare",
		"seize": "fang-howld",
		"sell": "sal",
		"sensitive": "muur-har'ed",
		"service": "sarvice",
		"seven": "seeven",
		"several": "savrul",
		"sewing": "sooin",
		"sex": "the other",
		"shade": "shairde",
		"shake": "shig",
		"sheaf": "shoof",
		"shed": "shud",
		"shell": "shuck",
		"shelter": "stand-up",
		"shire": "sheer",
		"shiver": "dudder",
		"shod": "shaard",
		"shop": "shaap",
		"shoping": "shaapin",
		"short": "haardy-daardy",
		"shout": "holler",
		"showed": "shoe",
		"showery": "dingin",
		"shrieked": "shruck",
		"shrivelled": "dwinged",
		"shy": "koi-ish",
		"sickle": "swoipe",
		"sickly": "dwainy",
		"sight": "soight",
		"silly": "shay-brairned",
		"sir": "sar",
		"skate": "patten",
		"skinned": "skun'",
		"sledge": "slaird",
		"sloven": "shammock",
		"slovenly": "shucky",
		"slush": "sluss",
		"smack": "thack",
		"small": "haardy-daardy",
		"smug": "koi-ish",
		"snack": "sunke'",
		"snail": "dodderman",
		"sneak": "draw-latch",
		"sniggering": "gimlin",
		"snob": "'alf-sixer",
		"snowed": "snew",
		"soft": "sorf'",
		"soldier": "swoddy",
		"something": "suffin",
		"sound": "deen",
		"sowed": "sue",
		"sowing": "sarn",
		"speech": "talk",
		"spin": "twizzle",
		"spit": "spawle-ou'",
		"splinter": "shiver",
		"split": "sprung",
		"spoke": "spook",
		"spot": "spaa'",
		"spread": "spreed",
		"sprightly": "kedgy",
		"squat": "dop-a-lowly",
		"squirm": "skriggle",
		"stale": "foisty",
		"stare": "gawp",
		"stew": "stuw",
		"sticky": "claggyg",
		"stiff": "stark",
		"stocky": "stuggy",
		"stone": "stoon",
		"storm": "tempest",
		"story telling": "yarmanderin",
		"stow": "bestow",
		"strangle": "grairn",
		"stream": "beck",
		"stress": "pucka-erry",
		"stride": "stroome",
		"stroke": "strook",
		"stroll": "lollop",
		"strolling": "lollopin along",
		"stuck-up": "baa'y",
		"stutter": "har-n-acker",
		"sueing": "surn",
		"sunday best": "becomes",
		"supercilious": "sneerfroys",
		"swam": "swum",
		"sweaty": "muckwash",
		"sweets": "cushies",
		"swelter": "mal'ud",
		"sweltering": "swallackin",
		"take": "tairke",
		"talkative": "spuffler",
		"teach": "larn",
		"tell": "tal",
		"telly": "tally",
		"temper": "passe",
		"tend": "fare-a",
		"tether": "tather",
		"that": "tha",
		"thatching": "thackin",
		"thaw": "tho",
		"thawed": "thew",
		"the": "thur",
		"themselves": "theirsalves",
		"they": "thay",
		"thighs": "strong-docked",
		"thirteen": "tha'een",
		"thirty": "tha'y",
		"thither": "yon",
		"three": "tree",
		"threshing": "troshin",
		"threshold": "troshel",
		"thrive": "addle",
		"throat": "strupe",
		"throb": "galver",
		"throttle": "grairn",
		"throw": "hull",
		"thrush": "mavish",
		"tight": "stark",
		"tiles": "pamments",
		"time": "toime",
		"tispy": "bosky",
		"tiptoe": "pample",
		"toad": "puddock",
		"toe": "tooe",
		"toffee": "tuffy",
		"together": "agatha",
		"tomorrow": "amara",
		"too": "anarl",
		"torn": "ren",
		"toss": "doss",
		"towel": "tarl",
		"towing": "tarn",
		"train": "trairn",
		"tramp": "moilstoon inspector",
		"travelling": "strammackin",
		"treat": "trea",
		"trowel": "trarl",
		"turn": "taan",
		"turnip": "tannup",
		"twelve": "twalve",
		"twenty": "twe'y",
		"unbeknown": "unbeknowns",
		"underneath": "unean",
		"underwear": "dissables",
		"unless": "withou",
		"unravel": "frazzle",
		"unsettled": "thredickle",
		"untidy": "wibbled",
		"upright": "uproigh",
		"waistcoat": "wesku",
		"wait": "wair",
		"was": "woos",
		"want": "wo'a",
		"wasn't": "woon",
		"washing": "puggin true",
		"wasn't": "woon",
		"wasp": "wapsy",
		"watery": "lash",
		"weaken": "disimprove",
		"weather": "wather",
		"well": "wal",
		"went": "wen'",
		"what": "waa",
		"what is": "wooss",
		"wheelbarrow": "crud-barrer",
		"whereas": "whereboi",
		"whereby": "whereboi",
		"whether": "wather",
		"whimper": "winnick",
		"whining": "grizzly",
		"whirlwind": "roger",
		"wholly": "hoolly",
		"wick": "snaste",
		"wicked": "wicke'",
		"wild": "shanny",
		"window": "lucam",
		"winkles": "pinpaunches",
		"without": "withou",
		"won't": "oon",
		"wood-pigeon": "dow",
		"woodlice": "sows",
		"word": "waad",
		"worn out": "begone",
		"worst": "waast",
		"worthless": "mucher",
		"wouldn't": "woon",
		"wrap": "hap",
		"wriggle": "arsle",
		"wrote": "wri'",
		"year": "yare",
		"yearn": "yaan",
		"yeast": "bargood",
		"yell": "yal",
		"yes": "yiss",
		"yesterday": "yisty",
		"yet": "yi'",
		"yolk": "yelk",
		"you": "yow",
		"you've": "yure",
		"yours": "yawn"
	}
};
